---
- hosts: all
  tasks:
    - name: Copy pcap file from ControlNode
      fetch:
        src: /home/sumaya/Desktop/pcaps.pcap
        dest: /home/sumaya/CPE243HOA8.1/
        flat: yes

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Extract executable file
      command: tcpflow -r /home/sumaya/CPE243HOA8.1/pcaps.pcap -o /home/sumaya/CPE243HOA8.1
      args:
        creates: /home/sumaya/CPE243HOA8.1/executable.exe

    - name: Debug.exe file
      command: cat /home/sumaya/CPE243HOA8.1/report.xml
      register: cat_output
      changed_when: false
 
    - debug:
        var: cat_output.stdout_lines
